name: Downstream Compatibility Check

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  downstream:
    uses: OpenVoiceOS/gh-automations/.github/workflows/downstream-check.yml@dev
    secrets: inherit
    with:
      package_name: 'ovos-yes-no-plugin'
      commit_branch: 'dev'
